# fly.toml app configuration file generated for capture-the-miles on 2023-09-04T17:29:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "capture-the-miles"
primary_region = "ams"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
